<a href="https://colab.research.google.com/github/PranavPD7/Movie_Recommendation/blob/main/Recommender_movies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import nltk
from nltk.stem.porter import PorterStemmer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords


In [ ]:
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
import difflib
import re
import os

In [ ]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
dataset=pd.read_csv('/content/drive/MyDrive/Copy of movies.csv')
dataset.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
dataset.isnull().sum()

index                   0
budget                  0
genres                  0
homepage                0
id                      0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
tagline                 0
title                   0
vote_average            0
vote_count              0
cast                    0
crew                    0
director                0
content                 0
dtype: int64

In [ ]:
dataset.fillna('',inplace=True)

<ipython-input-14-ae803a1dd6e0>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dataset.fillna('',inplace=True)


In [ ]:
combined_features=dataset['genres']+dataset['keywords']+dataset['title']+dataset['crew']+dataset['director']
combined_features

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceNewlyweds[{'name': 'Edward Burns...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    Shanghai Calling[{'name': 'Daniel Hsia', 'gend...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object

In [ ]:
vect=TfidfVectorizer()
feature_vectors=vect.fit_transform(combined_features)
print(feature_vectors)

  (0, 29008)	0.017898743762443547
  (0, 143279)	0.017898743762443547
  (0, 226730)	0.017898743762443547
  (0, 210084)	0.014833975863545476
  (0, 20854)	0.017898743762443547
  (0, 113854)	0.017898743762443547
  (0, 186109)	0.007544672214992857
  (0, 20853)	0.01707255193872719
  (0, 113853)	0.017898743762443547
  (0, 226276)	0.01707255193872719
  (0, 20852)	0.017898743762443547
  (0, 113852)	0.017898743762443547
  (0, 221835)	0.017898743762443547
  (0, 20851)	0.01707255193872719
  (0, 113850)	0.017898743762443547
  (0, 215671)	0.01707255193872719
  (0, 213896)	0.009927450162470434
  (0, 20850)	0.017898743762443547
  (0, 113848)	0.017898743762443547
  (0, 211820)	0.017898743762443547
  (0, 218832)	0.014084685232509511
  (0, 20849)	0.017898743762443547
  (0, 113845)	0.017898743762443547
  (0, 209669)	0.01603167333965503
  (0, 208926)	0.013206904836724308
  :	:
  (4802, 215796)	0.184182923515928
  (4802, 191914)	0.17910324365932914
  (4802, 192396)	0.16115465877914195
  (4802, 226828)	0.122

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
selected_features=cosine_similarity(feature_vectors)
print(selected_features)

[[1.         0.58050872 0.82468577 ... 0.36623655 0.10218556 0.22500272]
 [0.58050872 1.         0.58799315 ... 0.33480688 0.08947772 0.20040266]
 [0.82468577 0.58799315 1.         ... 0.38268475 0.11038233 0.23093832]
 ...
 [0.36623655 0.33480688 0.38268475 ... 1.         0.06161315 0.14372219]
 [0.10218556 0.08947772 0.11038233 ... 0.06161315 1.         0.04045468]
 [0.22500272 0.20040266 0.23093832 ... 0.14372219 0.04045468 1.        ]]


In [ ]:
movie=input('enter favourite movie name')


enter favourite movie nameiron man


In [ ]:
close_match=difflib.get_close_matches(movie,dataset['title'])
print(close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [ ]:
closest_match=close_match[0]

In [ ]:
index=dataset['index'][dataset['title']==closest_match]
print(index)

68    68
Name: index, dtype: int64


In [ ]:
print(selected_features[index][0])

[0.49323663 0.42131001 0.51338171 ... 0.28582961 0.07823407 0.1816672 ]


In [ ]:
movies=[]
for i,v in enumerate(selected_features[index][0]):
  movies.append((i,v))


In [ ]:
print(movies)

[(0, 0.49323662558693054), (1, 0.42131001195513396), (2, 0.5133817134684414), (3, 0.5229015650629751), (4, 0.5044316397433192), (5, 0.48496668342851024), (6, 0.4474554064073591), (7, 0.5285067354253267), (8, 0.3817772031762008), (9, 0.5255043694306358), (10, 0.38952905338395), (11, 0.3627328005216443), (12, 0.3811658769432747), (13, 0.41644947532456017), (14, 0.467112462777042), (15, 0.48604886757263627), (16, 0.5266210771844949), (17, 0.42974365089002137), (18, 0.3715741199750182), (19, 0.5057369629852863), (20, 0.519331545031134), (21, 0.34572965322330146), (22, 0.5097548844136347), (23, 0.4131983601287278), (24, 0.42305762302996264), (25, 0.46699969703176675), (26, 0.536872799193162), (27, 0.5063651327926181), (28, 0.5230135805881652), (29, 0.40782719169362674), (30, 0.5339848397182838), (31, 0.5178683878380435), (32, 0.38778919461682426), (33, 0.4886578083787074), (34, 0.307100272369535), (35, 0.47245393482393505), (36, 0.4860514981124091), (37, 0.4041480189433657), (38, 0.52356925

In [ ]:
movies=np.array(movies)
movies

array([[0.00000000e+00, 4.93236626e-01],
       [1.00000000e+00, 4.21310012e-01],
       [2.00000000e+00, 5.13381713e-01],
       ...,
       [4.80000000e+03, 2.85829608e-01],
       [4.80100000e+03, 7.82340721e-02],
       [4.80200000e+03, 1.81667199e-01]])

In [ ]:
recommended_movies=movies[movies[:,1].argsort()]
print(recommended_movies)

[[3.66100000e+03 0.00000000e+00]
 [4.12300000e+03 0.00000000e+00]
 [3.97700000e+03 0.00000000e+00]
 ...
 [1.82000000e+02 5.46325637e-01]
 [7.90000000e+01 6.04437417e-01]
 [6.80000000e+01 1.00000000e+00]]


In [ ]:
recommended_movies.shape

(4803, 2)

In [ ]:
movie_ids=[]
for i in range(4802,-1,-1):
  movie_ids.append(recommended_movies[i,0])
movie_ids=np.array(movie_ids)


In [ ]:
movie_ids

array([  68.,   79.,  182., ..., 3977., 4123., 3661.])

In [ ]:
movie_recommendations=[]
for i in range(0,30):
  movie_recommendations.append(list(dataset['title'].values[dataset['index']==movie_ids[i]]))

In [ ]:
print(movie_recommendations)

[['Iron Man'], ['Iron Man 2'], ['Ant-Man'], ['Hulk'], ['Blade: Trinity'], ['Spider-Man'], ['Captain America: Civil War'], ['Terminator 3: Rise of the Machines'], ['Spider-Man 2'], ['Alexander'], ['Catwoman'], ['The Core'], ['Elektra'], ['Blade II'], ['Blade'], ['Bad Boys II'], ['Cursed'], ['Avengers: Age of Ultron'], ['The Chronicles of Riddick'], ['The Punisher'], ['The Aviator'], ['The Avengers'], ['Batman v Superman: Dawn of Justice'], ['Scary Movie 2'], ['Master and Commander: The Far Side of the World'], ['Scary Movie 3'], ['The Day After Tomorrow'], ['Minority Report'], ['Contact'], ['Fantastic Four']]
